name: "Terraform Windows VM Deployment"

on:
  push:
    paths:
      - "windows/**"
  pull_request:
    paths:
      - "windows/**"

jobs:
  terraform:
    name: "Terraform Windows VM"
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      # Log in to Azure using the Service Principal
      - name: "Azure Login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      # Set up Terraform
      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      # Initialize Terraform
      - name: "Terraform Init"
        run: terraform init -backend-config="windows/backend-config.tfbackend"
        working-directory: windows/
        env:
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Format Terraform files
      - name: "Terraform Format"
        run: terraform fmt -check
        working-directory: windows/

      # Validate Terraform configuration
      - name: "Terraform Validate"
        run: terraform validate
        working-directory: windows/

      # Terraform Plan
      - name: "Terraform Plan"
        run: terraform plan
        working-directory: windows/
        env:
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Apply the Terraform changes
      - name: "Terraform Apply"
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: windows/
        env:
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
